# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDFparser(object):
    def setupUi(self, PDFparser):
        PDFparser.setObjectName("PDFparser")
        PDFparser.resize(676, 362)
        self.mdiArea = QtWidgets.QMdiArea(PDFparser)
        self.centralwidget = self.mdiArea
        self.centralwidget.setObjectName("centralwidget")
        PDFparser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PDFparser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        PDFparser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PDFparser)
        self.statusbar.setObjectName("statusbar")
        PDFparser.setStatusBar(self.statusbar)
        self.actionOpen_sample = QtWidgets.QAction(PDFparser)
        self.actionOpen_sample.setObjectName("actionOpen_sample")
        self.actionExit = QtWidgets.QAction(PDFparser)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionOpen_sample)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(PDFparser)
        QtCore.QMetaObject.connectSlotsByName(PDFparser)

    def retranslateUi(self, PDFparser):
        _translate = QtCore.QCoreApplication.translate
        PDFparser.setWindowTitle(_translate("PDFparser", "PDF parser"))
        self.menuMenu.setTitle(_translate("PDFparser", "Menu"))
        self.actionOpen_sample.setText(_translate("PDFparser", "Open sample"))
        self.actionExit.setText(_translate("PDFparser", "Exit"))
